const toast=document.querySelector('#toast');let toastTimer;function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),5500)}document.querySelectorAll('[data-notice]').forEach(b=>b.addEventListener('click',()=>notify(b.dataset.notice)));
const tabs=[...document.querySelectorAll('[role="tab"]')];function selectTab(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected})}tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;if(e.key==='ArrowLeft')next=(i-1+tabs.length)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();selectTab(tabs[next]);tabs[next].focus()}})});
const dialog=document.querySelector('#project-dialog');document.querySelector('#project-open').addEventListener('click',()=>dialog.showModal());dialog.querySelectorAll('.dialog-close,.dialog-done').forEach(b=>b.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const stage=document.querySelector('.portrait-stage'),portrait=document.querySelector('#portrait-card');const motion=matchMedia('(prefers-reduced-motion: reduce)'),pointer=matchMedia('(pointer:fine)');stage.addEventListener('pointermove',e=>{if(motion.matches||!pointer.matches)return;const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;portrait.style.transform=`rotateX(${-y*8}deg) rotateY(${x*10}deg) rotateZ(4deg)`});stage.addEventListener('pointerleave',()=>portrait.style.transform='');motion.addEventListener('change',()=>portrait.style.transform='');
document.querySelector('#year').textContent=new Date().getFullYear();const links=[...document.querySelectorAll('nav a')];const obs=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.hash==='#'+entry.target.id))})},{rootMargin:'-10% 0px -55% 0px'});links.forEach(a=>obs.observe(document.querySelector(a.hash)));

// Preserve the blue palette while switching neutral surfaces.
const themeToggle=document.querySelector('#theme-toggle');function syncTheme(){const dark=document.documentElement.dataset.theme==='dark';themeToggle.setAttribute('aria-pressed',String(dark));themeToggle.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');themeToggle.firstElementChild.textContent=dark?'☀':'☾'}syncTheme();themeToggle.addEventListener('click',()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('omer-theme',theme)}catch{}syncTheme()});
(async()=>{const deck=document.querySelector('#document-deck'),dots=document.querySelector('#deck-dots'),viewer=document.querySelector('#document-viewer'),viewport=document.querySelector('#document-viewport'),image=document.querySelector('#viewer-image');let documents=[],active=0,zoom=1,start=null,moved=false,fitWidth=760;
try{const response=await fetch('documents/documents.json');if(!response.ok)throw Error('Documents unavailable');documents=await response.json()}catch{deck.textContent='Documents could not be loaded. Please refresh or download the collection.';document.querySelector('#document-prev').disabled=true;document.querySelector('#document-next').disabled=true;return}
const cards=documents.map((doc,i)=>{const b=document.createElement('button');b.className='floating-document';b.type='button';b.setAttribute('aria-label',`Open ${doc.title}`);const img=document.createElement('img');img.src=doc.image;img.alt=`Original document ${i+1}: ${doc.title}`;img.draggable=false;b.append(img);b.addEventListener('click',()=>{if(moved)return;if(i===active)openViewer();else show(i)});return b});deck.replaceChildren(...cards);const dotButtons=documents.map((doc,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',`Show ${doc.title}`);b.addEventListener('click',()=>show(i));dots.append(b);return b});
function show(index){active=(index+documents.length)%documents.length;cards.forEach((b,i)=>{const position=(i-active+documents.length)%documents.length;b.dataset.position=String(position);b.hidden=position>2&&position<documents.length-2;if(position===documents.length-1)b.dataset.position="5";else if(position===documents.length-2)b.dataset.position="4";b.tabIndex=i===active?0:-1});dotButtons.forEach((b,i)=>b.setAttribute('aria-current',String(i===active)));const d=documents[active];document.querySelector('#document-title').textContent=d.title;document.querySelector('#document-category').textContent=`${String(active+1).padStart(2,'0')} / ${String(documents.length).padStart(2,'0')} · ${d.category}`;document.querySelector('#document-issuer').textContent=`${d.issuer} · ${d.date}`;if(viewer.open)renderViewer()}
function zoomImage(){image.style.width=`${Math.round(fitWidth*zoom)}px`;document.querySelector('#zoom-level').textContent=`${Math.round(zoom*100)}%`;document.querySelector('#zoom-out').disabled=zoom<=.5;document.querySelector('#zoom-in').disabled=zoom>=3;document.querySelector('#zoom-fit').disabled=false}
function renderViewer(){const d=documents[active];zoom=1;const download=document.querySelector('#viewer-download');download.href=d.download||'documents/omer-original-documents.pdf';download.download=d.downloadName||'Omer-Original-Documents.pdf';download.textContent=d.download?'Download photo ↓':'Download PDF ↓';document.querySelector('#viewer-title').textContent=d.title;document.querySelector('#viewer-counter').textContent=`DOCUMENT ${active+1} OF ${documents.length} · ${d.date}`;image.onload=()=>{viewport.scrollTop=0;viewport.scrollLeft=0};image.src=d.image;image.alt=`Original document ${active+1}: ${d.title}. Text and layout unchanged.`;fitWidth=Math.min(900,viewport.clientWidth-(innerWidth<=570?16:40));zoomImage();viewport.scrollTop=0;viewport.scrollLeft=0}
function openViewer(){viewer.showModal();renderViewer();document.querySelector('#viewer-close').focus()}
function shift(n){show(active+n)}document.querySelector('#document-prev').addEventListener('click',()=>shift(-1));document.querySelector('#document-next').addEventListener('click',()=>shift(1));document.querySelector('#viewer-prev').addEventListener('click',()=>shift(-1));document.querySelector('#viewer-next').addEventListener('click',()=>shift(1));document.querySelector('#viewer-close').addEventListener('click',()=>viewer.close());viewer.addEventListener('close',()=>cards[active].focus());
deck.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();shift(e.key==='ArrowLeft'?-1:1)}else if(e.key==='Enter'&&e.target===deck){e.preventDefault();openViewer()}});viewer.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){if(zoom===1){e.preventDefault();shift(e.key==='ArrowLeft'?-1:1)}}});
deck.addEventListener('pointerdown',e=>{if(e.button!==0)return;start={x:e.clientX,y:e.clientY};moved=false});deck.addEventListener('pointermove',e=>{if(start&&Math.abs(e.clientX-start.x)>12)moved=true});function finishSwipe(e){if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)){moved=true;shift(dx<0?1:-1)}start=null;setTimeout(()=>moved=false,100)}deck.addEventListener('pointerup',finishSwipe);deck.addEventListener('pointercancel',()=>{start=null;moved=false});deck.addEventListener('pointerleave',e=>{if(e.pointerType==='mouse')start=null});
document.querySelector('#zoom-in').addEventListener('click',()=>{zoom=Math.min(3,zoom+.25);zoomImage()});document.querySelector('#zoom-out').addEventListener('click',()=>{zoom=Math.max(.5,zoom-.25);zoomImage()});document.querySelector('#zoom-fit').addEventListener('click',()=>{zoom=1;fitWidth=Math.min(900,viewport.clientWidth-(innerWidth<=570?16:40));zoomImage();viewport.scrollLeft=0});window.addEventListener('resize',()=>{if(viewer.open&&zoom===1){fitWidth=Math.min(900,viewport.clientWidth-(innerWidth<=570?16:40));zoomImage()}});document.querySelectorAll('[data-document]').forEach(button=>button.addEventListener('click',()=>{const index=documents.findIndex(d=>d.id===button.dataset.document);if(index>=0){show(index);openViewer()}}));show(0);
})();
